### ISSUE TITLE
Musím dvakrát kliknout abych mohl generovat fakta

### ISSUE THREAD

**Issue by HelloWorld7894** [Plajta/PlzenskyPoharPravdy#1]
Hoj @Vesek myslím že jsem zjistil příčínu toho proč musím dvakrát kliknout abych mohl generovat fakta.

Kouknul jsem se do web console, a zjistil jsem že z nějakého důvodu se frontend nemůže připojit na websocket server na backendu (Posílám obrázek)

![image](https://github.com/Plajta/PlzenskyPoharPravdy/assets/59885570/586cd703-33d3-4906-b21a-39c064f97051)

Takže buď @salivo udělal někde chybu s připojováním v Reactu (silně pochybuju, local to funguje) a nebo to musí být chyba u tebe na serveru.

Každopádně jsem vás mezi assignees hodil oba dva :)

**Comment by salivo** [comment]
Ok, kouknu zítra možná bude u mě chyba
Možná @Vesek nemá na serveru fetchnuto nějaká data?

**Comment by HelloWorld7894** [comment]
To spíš vypadá, že se frontend neumí připojit k serveru, nemohlo by to být tak že by tam @Vesek měl přes UFW zablokované porty které jsou využívány websockety?

**Comment by Vesek** [comment]
Socket.IO používá HTTPS takže porty to bejt nemůžou, UFW nemam, a děje se to i localhostu.
Je ale dost možný že za to může generátor faktů

**Comment by Vesek** [comment]
Ale je pravda že jsem slišel o tom že flask-socketio má občas problémy s reverse proxy, teď to řešit nebudu ale jednou se na to podívam

**Comment by HelloWorld7894** [comment]
Vypadá to, že chyba je jiná u každého browseru, teď jsem zkoušel nainstalovat chromium a dostávám jinej error
![image](https://github.com/Plajta/PlzenskyPoharPravdy/assets/59885570/bcc3fd48-3e07-46a9-be52-13d3a98e10e6)

Myslím že problém je ten, že máme špatně nastavenej responses na backendu, protože z nějakého důvodu je frontend nespokojenej s code 200 (OK)

Na firefoxu dostávám zase error:
![image](https://github.com/Plajta/PlzenskyPoharPravdy/assets/59885570/014af4f2-f8f4-426b-866e-6cefed9d7f45)

Přičemž co tak koukám do frontend kódu, tak tam adresa není speifikovaná, tak nevím jestli tohle náhodou nedělá problém, každopádně mám menší obavy že na všechny requesty v backendu vracíme 200

**Comment by Vesek** [comment]
Opraveno, na použití Socket.IO connection upgradu je potřeba Nginx říct kam to má redirectovat viz [zde](https://flask-socketio.readthedocs.io/en/latest/deployment.html#using-nginx-as-a-websocket-reverse-proxy)

**Comment by HelloWorld7894** [comment]
:)
