### ISSUE TITLE
Renderování měst v topbaru nefunguje

### ISSUE THREAD

**Issue by HelloWorld7894** [Plajta/PlzenskyPoharPravdy#11]
Po nejnovějším api key updatu je fetchování měst lehce rozbité, kdykoliv totiž jdu pryč z prahy markerem, město prostě zmizí.
Např.:

![image](https://github.com/Plajta/PlzenskyPoharPravdy/assets/59885570/b9fa3463-888f-4e47-a83e-ad24d36179f3)
Topbar měl nahoře ukazovat **Neratovice**. 

Vypadá to, že to bude něco v backendu, protože v konzoli ve frontendu dostávám na *řádce 178* v `index.js` zprávu `<empty string>`

![image](https://github.com/Plajta/PlzenskyPoharPravdy/assets/59885570/97e67acd-a715-4ed1-b6aa-8e7a3dc9c767)

problém asi bude s socketem `send_city`

**Comment by salivo** [comment]
problem je v Rest API nedostávám města

**Comment by HelloWorld7894** [comment]
To je divný, @LosVocelos na tomhle během hackathonu pracoval a normálně by měl z backendu tyto data posílat tobě na frontend, trošku si myslím že problém bude se změnou klíče, je možné že ho ještě někde v backendu používáme a díky tomu nemůžeme udělat query na Mapy.cz API

**Comment by HelloWorld7894** [comment]
![image](https://github.com/Plajta/PlzenskyPoharPravdy/assets/59885570/5fdb87e2-91aa-469d-afa8-3485aa760caf)
@LosVocelos já tě asi zabim, to je podruhé co nám někde leaknul API key v source kódu. Prosímvás klucí, na tohle si musíme dát pozor, každopádně jdu to opravit, v dalším commitu se bude používat global variable kterej je čtenej v YAMLu a já tímto zavírám tenhle issue.
