### ISSUE TITLE
Udělat možnost bez fetchování polohy

### ISSUE THREAD

**Issue by HelloWorld7894** [Plajta/PlzenskyPoharPravdy#4]
Když nedáte přístup k fetchování polohy, tak vás prostě aplikace nebude mít ráda a nedá vám žádnej marker k dispozici, takže musíte zmáčknout generate aby se vám to "odbugovalo".

Přidal bych aspoň nějakej timeout, po kterém se to prostě přestane snažit.
Jo a pak bych tam přidal taky button na opakované fetchování pozice.

**Comment by salivo** [comment]
To actually musím udělat.

**Comment by salivo** [comment]
hotovo enjoy
